version: '3'
services:
  chinadns:
    build: chinadns/.
    depends_on:
      - proxy-dns
    restart: always
    networks:
      net-cnsmartdns:
        ipv4_address: 10.5.0.3

  proxy-dns:
    build: proxy-dns/.
    restart: always
    networks:
      net-cnsmartdns:
        ipv4_address: 10.5.0.2

  dnsmasq:
    build: dnsmasq/.
    depends_on:
      - chinadns
      - proxy-dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always
    networks:
      net-cnsmartdns:
        ipv4_address: 10.5.0.1
networks:
  net-cnsmartdns:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16